-- Database access
GRANT USAGE ON DATABASE DEMO1_DB TO ROLE DEMO1_ROLE;

-- Schemas
GRANT USAGE ON SCHEMA DEMO1_DB.SCHEMA_A TO ROLE DEMO1_ROLE;
GRANT USAGE ON SCHEMA DEMO1_DB.SCHEMA_B TO ROLE DEMO1_ROLE;
GRANT USAGE ON SCHEMA DEMO1_DB.SCHEMA_C TO ROLE DEMO1_ROLE;

-- Tables
GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA DEMO1_DB.SCHEMA_A TO ROLE DEMO1_ROLE;

GRANT SELECT
ON ALL TABLES IN SCHEMA DEMO1_DB.SCHEMA_B TO ROLE DEMO1_ROLE;

-- Future-proofing
GRANT SELECT
ON FUTURE TABLES IN SCHEMA DEMO1_DB.SCHEMA_A TO ROLE DEMO1_ROLE;
